spring.application.name=gustos-page-backend

server.port=${PORT:8080}

app.cors.origins=${APP_CORS_ORIGINS:http://localhost:*}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

security.jwt.user.generator=${USER_GENERATOR}
security.jwt.secret.key=${SECRET_KEY}
security.jwt.ttl-seconds=${JWT_TTL}
security.jwt.refresh.ttl-seconds=${JWT_REFRESH_TTL}
app.cookies.secure=${COOKIES_SECURE:true}
app.cookies.same-site=${COOKIES_SAME_SITE:None}

spring.jpa.show-sql=false

logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO

spring.main.lazy-initialization=false
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:false}

app.admin.username=${ADMIN_USERNAME}
app.admin.password=${ADMIN_PASSWORD}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never